# Open ports 22,80,443 (tcp)

- name: Open ports 22,80,443 in iptables (tcp)
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_ports:
      - "80"
      - "443"
      - "22"
    jump: ACCEPT
