# Base system initialization

- name: Update apt cache
  ansible.builtin.apt: update_cache=yes

# No requirements for git version so use lastest
- name: Install git
  ansible.builtin.apt: name=git state=present

# Include iptables task
- name: Include iptables task
  ansible.builtin.include_tasks: iptables.yml
