# Install lavarel from git
- name: Clone lavarel repo
  become: true
  become_user: www-data
  git:
    repo: https://github.com/laravel/laravel.git
    dest: /var/www/{{ serverName }}
    force: yes

- name: Set permissions for Laravel storage folder
  file:
   path: /var/www/{{ serverName }}/storage
   state: directory
   recurse: yes
   mode: '0755'

- name: Install laravel dependencies
  become: true
  become_user: www-data
  community.general.composer:
   command: update
   working_dir: /var/www/{{ serverName }}

# - name: copy env file
#   copy:
#    src: /var/www/{{ serverName }}/.env.example
#    remote_src: yes
#    dest: /var/www/{{ serverName }}/.env
#    owner: www-data
#    group: www-data
#    mode: '0644'

# No idempotency must fix it
- name: Create .env file
  template:
   src: env.j2
   dest: /var/www/{{ serverName }}/.env
   owner: www-data
   group: www-data
   mode: '0644'

# - name: setup laravel
#   shell: |
#         cd /var/www/{{ serverName }}
#         php artisan key:generate
