# Install composer
- name: Check if composer is installed
  ansible.builtin.stat:
    path: /usr/bin/composer
  register: composer_binary

- name: Download Composer installer
  when: not composer_binary.stat.exists
  ansible.builtin.get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-setup.php

- name: Install composer
  ansible.builtin.command: php /tmp/composer-setup.php --install-dir=/usr/bin --filename=composer
  when: not composer_binary.stat.exists

- name: Update to latest composer version
  ansible.builtin.command: composer selfupdate
  when: composer_binary.stat.exists
  changed_when: false
