# Nginx confinguration

- name: Make sure apache related packages are removed
  ansible.builtin.apt: name="{{ packages }}" state=absent purge=yes
  vars:
      packages:
          - apache2
          - apache2-utils

- name: Install nginx
  ansible.builtin.apt: name=nginx state=present
- name: Make sure nginx user exists
  ansible.builtin.user:
      name: nginx
      comment: nginx user
      createhome: false
      generate_ssh_key: false
      shell: /bin/false
      system: true

- name: Configure nginx site
  ansible.builtin.template: src=nginx-virtualhost.conf.j2 dest=/etc/nginx/sites-available/{{ serverName }}.conf

- name: Enable nginx site
  ansible.builtin.file:
      src: /etc/nginx/sites-available/{{ serverName }}.conf
      dest: /etc/nginx/sites-enabled/{{ serverName }}.conf
      state: link

- name: Disable default nginx site
  ansible.builtin.file:
      path: /etc/nginx/sites-enabled/default
      state: absent
  notify:
      - Restart nginx

- name: Make sure nginx is restarted and is started on boot
  ansible.builtin.service: name=nginx state=restarted enabled=yes

- name: Create site directory
  ansible.builtin.file: path=/var/www/{{ serverName }} state=directory owner=www-data group=www-data mode=0775
