# Installing php

- name: Install PHP and extensions
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - php{{ phpVersion }}
    - php{{ phpVersion }}-zip
    - php{{ phpVersion }}-mbstring
    - php{{ phpVersion }}-xml
    - php{{ phpVersion }}-mysqlnd
    - php{{ phpVersion }}-curl

- name: Install php-fpm
  apt: name=php{{ phpVersion }}-fpm state=present

- name: Make sure php-fpm is running
  service: name=php{{ phpVersion }}-fpm state=started enabled=yes
